version: '3'
services:
  ycsb:
    image: torusware/speedus-ycsb
    hostname: "ycsb"
    container_name: ycsb
    volumes:
       - ..:/code
    tty: true
    privileged: true
    networks:
      mynetwork:
        aliases:
          - ycsb
          - ycsb.localdomain.com
  gpdb5:
        #build:
        #  context: .
        #  dockerfile: ./gpdb/Dockerfile
        image: "kochanpivotal/gpdb5-pxf"
        command: bin/bash
        hostname: "gpdbsne"
        container_name: gpdbsne
        ports:
         - "5432:5432"
         - "5005:5005"
         - "5010:5010"
         - "9022:22"
         - "40000:40000"
         - "40001:40001"
         - "40002:40002"
         - "28080:28080"
        expose:
         - "5432"
        volumes:
         - ..:/code
        privileged: true
        tty: true
        networks:
          mynetwork:
            aliases:
              - gpdbsne
              - gpdbsne.localdomain.com
networks:
    mynetwork:
      driver: bridge
